// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhtywvglxtctmjqwkzjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1odHl3dmdseHRjdG1qcXdrempwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzI2MTksImV4cCI6MjA2MDUwODYxOX0.KPlakndc2sCaRdOk0K0_I0pWB1q80_hgV5kI8CacU4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);